name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Populate install file
      run: |
        tag=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
        sed -i "s/VERSION/$tag/g" install-reLuminate.sh

    #- name: Get tag message
    #  run: |
    #    tag=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
    #    # manually fetch the tag, otherwise commit message is found
    #    git fetch --depth=1 origin +refs/tags/"$tag":refs/tags/"$tag"
    #    message=$(git tag -l "$tag" --format '%(contents)')
    #    echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
    #    echo "$message" >> $GITHUB_ENV
    #    echo "EOF" >> $GITHUB_ENV

    - name: Upload release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          install-reLuminate.sh
        body: ${{ env.RELEASE_NOTES }}

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
